cd ../..
python manage.py sqlmigrate $1 $2

# $1 = app name
# $2 = migration number integre

# example
# ./sqlMigrate polls 0001

# Create sql script for migrations
# example: CREATE TABLE "polls_question" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question_text" ...

